[package]
name = "too-many-lists"
version = "0.1.0"
authors = ["Richard Pringle <rpring9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "lib"
